Update Jenkinsfile_Testsuite

diff --git a/Jenkinsfile_Testsuite b/Jenkinsfile_Testsuite
--- a/Jenkinsfile_Testsuite
+++ b/Jenkinsfile_Testsuite
@@ -5,18 +5,15 @@ pipeline {
             steps {
                 echo "Generating Test Suite project file from Foundation model"
           
-                bat "sh -x ./testsuitescript/codeconvertor.sh"
-      
-                 
+                bat "sh -x ./testsuitescript/codeconvertor.sh"         
             }
         }
 
         stage("Commit Generated Files") {
             steps {
-		echo "Staging the generated files and commiting in git"
-             
-          //  bat "git add ./Design.doc"
-          //  bat "git commit -m 'AIGeneratedFiles' || echo 'Commit failed. There is probably nothing to commit.'"
+		echo "Staging the generated files and commiting in git"             
+          	//  bat "git add ./Design.doc"
+          	//  bat "git commit -m 'AIGeneratedFiles' || echo 'Commit failed. There is probably nothing to commit.'"
             }
         }
 
@@ -24,8 +21,6 @@ pipeline {
             steps {
                withCredentials([gitUsernamePassword(credentialsId: 'PAT_Jenk', gitToolName: 'Default')]) {
 		     echo "Pushing to remote GitHub Repo"
-	          //   bat "git pull origin main"		
-                  //   bat "git push -u origin main"
 		  //   bat "git push https://github.com/Sakshi-Git1/NewVersion.git HEAD:main"
                 }
             }
