Update Jenkinsfile_Testsuite

diff --git a/Jenkinsfile_Testsuite b/Jenkinsfile_Testsuite
--- a/Jenkinsfile_Testsuite
+++ b/Jenkinsfile_Testsuite
@@ -9,7 +9,7 @@ pipeline {
 		   
     //    withEnv(['PATH+EXTRA=/usr/sbin:/usr/bin:/sbin:/bin']) {  
           
-      //      bat "sh -x ./script/codeconvertor.sh WebApplication2/WebApplication2/Program.cs"
+       bat "sh -x ./designscript/codeconvertor.sh demo1/src/main/java/com/example/demo/main.java > Design.doc"
       
      
 //      }
@@ -33,8 +33,8 @@ pipeline {
               //  bat "git stash pop"     
 		//   bat "git config --global user.email 'agrasaks.in.ibm.com'"
 		  //  bat "git config --global user.name 'Sakshi-Git1'"
-                //bat "git add ./demo1/src/main/java/com/example/demo/main.java"
-                //bat "git commit -m 'AIGeneratedFiles' || echo 'Commit failed. There is probably nothing to commit.'"
+                bat "git add ./Design.doc"
+                bat "git commit -m 'AIGeneratedFiles' || echo 'Commit failed. There is probably nothing to commit.'"
             }
         }
 
@@ -44,42 +44,12 @@ pipeline {
 		     echo "Pushing to remote GitHub Repo"
 	          //   bat "git pull origin main"		
                   //   bat "git push -u origin main"
-		  //     bat "git push https://github.com/Sakshi-Git1/NewVersion.git HEAD:main"
+		       bat "git push https://github.com/Sakshi-Git1/NewVersion.git HEAD:main"
                 }
             }
         }
 
-        stage("Sync Repository") {
-            steps {
-                 echo "Sync working directory with remote GitHub Repo"
-                //    bat "git pull origin main"
-		  //  bat "git status"	 
-            }
-        }
-        stage('Build Docker image') {
-            steps {
-                echo "Building the docker Image based on Dockerfile"
-	        bat "cd demo1 & dos2unix mvnw & docker build -t sakshidocker12/hackthon-23 . --no-cache=true"
-		//sh "cd demo1 & chmod a+rw . & dos2unix mvnw & docker build -t sakshidocker12/hackthon-23 . --no-cache=true"
-            }
-        } 
+       
 
-        stage('Push Docker image') {
-            environment {
-		DOCKERHUB_CREDENTIALS = credentials('sakshidocker12-token')    
-            }
-            steps {
-		 echo "Shiping the Docker Image to DockerHub"    
-		 sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'    
-		 bat "docker push sakshidocker12/hackthon-23:latest"  
-		 bat "docker logout"  
-            }
         }
-        stage('Deploy to AWS') {
-             steps {
-                echo "Deploying the Docker Image on AWS -EC2"  
-                build job: "Deploy", wait: true
-              }
-           }
-       }
 }
